# Generated by Django 4.1 on 2022-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='blog',
            field=models.URLField(blank=True),
        ),
    ]
