# Generated by Django 4.1 on 2022-10-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_certificates_create_at_experiencia_create_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolioitem", old_name="replit", new_name="url",
        ),
    ]
