# Generated by Django 4.1 on 2022-08-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Certificates'},
        ),
    ]
