# Generated by Django 4.1 on 2022-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_certificates_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Experiencia',
            },
        ),
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Certificate'},
        ),
    ]
